### ISSUE TITLE
Vim key bindings

### ISSUE THREAD

**Issue by sfahlberg** [calleerlandsson/pick#146]
I love pick and use it in vim (pick.vim). I was wondering if there's a way to use vim bindings for navigating around pick, instead of the current emacs bindings, either in my .vimrc or some other way.

**Comment by mptre** [comment]
That would be tricky since all entered printable characters are treated
as part of the search query, including `hjkl`. There's currently no
concept of different modes like the ones found in Vim.

**Comment by calleerlandsson** [comment]
Hey @sfahlberg, thanks for the feedback!

This feature is currently not implemented in Pick.

Like @mptre suggests, this would require the concept of modes similar to Vim's insert and normal mode in Pick.

I think it is a good idea and would be happy review a PR implementing it. As always, my concern is added complexity but it's hard to make that decision without first seeing the implementation.

Would you want to work on this?

**Comment by mptre** [comment]
An alternative would be to use a existing library such as editline[1][2]
for the user input which supports Vi-mode. I haven't yet made up my mind
if this is a good idea or not.

[1] http://man.openbsd.org/OpenBSD-current/man3/editline.3
[2] http://man.openbsd.org/OpenBSD-current/man7/editline.7

**Comment by calleerlandsson** [comment]
Good point, @mptre! I haven't used editline previously but would be interested in seeing what using it would look like.

**Comment by rafaelrinaldi** [comment]
It would be great to be able to move up and down with `<C-k>` and `<C-j>` as well 👍

**Comment by DBOTW** [comment]
Very simple emulation of the `vi` command mode: https://github.com/DBOTW/pick/commit/e1ddef5ae1792fbfc94e6dc89e731f226e3124b1 ...

**Comment by calleerlandsson** [comment]
Closing this after the discussion in #261. Thanks, @DBOTW!
