### ISSUE TITLE
Pick not working with Bash's `shell-expand-line` binding

### ISSUE THREAD

**Issue by teoljungberg** [calleerlandsson/pick#177]
The option `shell-expand-line` in bash expands the line with a subshell present into the result of that subshell.

Example:

```sh
% echo $(printf "%f" 3.5)
# -----------------------^
# Enter keypress: \e\C-e
% echo 3.500000
# -------------^
```

The use-case for `pick(1)` would be to perform an action on a file that was selected from pick itself.

i.e

```sh
% cat $(git ls-files | pick)
# --------------------------^
# Enter keypress: \e\C-e
```

The problem is that neither `| pick` or `| pick -X` can perform an enter key-press to (in lack of a better word) "complete" the subshell. This has been tested with `"$()"` aswell as double back-tricks.
Strangely though, `C-j` works in place for the `CR`.

This works in `zsh` using their `expand-or-complete` command (mapped to `C-i`) with both `CR` and `C-j` to "complete" the subshell.

**Comment by mptre** [comment]
Looks like `\r` is sent rather than `\n`. Does the following patch solve
the problem?

```diff
diff --git a/pick.c b/pick.c
index 2a433fc..1ada630 100644
--- a/pick.c
+++ b/pick.c
@@ -756,6 +756,7 @@ get_key(char *buf, size_t size, size_t *nread)
 		int		 key;
 	}	keys[] = {
 		{ "\n",		1,	ENTER },
+		{ "\r",		1,	ENTER },
 		{ "\177",	1,	BACKSPACE },
 		{ "\001",	1,	CTRL_A },
 		{ "\002",	1,	LEFT },
```

**Comment by teoljungberg** [comment]
@mptre That indeed resolves the issue. Can you open a PR with that fix?

**Comment by mptre** [comment]
Done. Could the issue be closed in favor of the PR?

**Comment by teoljungberg** [comment]
Done and done.
