### ISSUE TITLE
Texts are not aligned and position change while I scroll down...

### ISSUE THREAD

**Issue by jamespanda** [calleerlandsson/pick#184]
work fine while all texts are English or numbers...
![2017-04-15-165730_1919x1020_scrot](https://cloud.githubusercontent.com/assets/14955228/25062358/94992770-21fd-11e7-99ea-2249c0e18ef6.png)
![2017-04-15-170349_1919x1019_scrot](https://cloud.githubusercontent.com/assets/14955228/25062359/949c3db6-21fd-11e7-843a-a94ff1bdacd9.png)

**Comment by mptre** [comment]
Hi,
Could you submit the following info:

- Version of pick: `pick -v`

- OS: `uname -a`

- Shell: `echo $SHELL`

- Locale: `echo $LC_CTYPE`

- The input file used in your screenshots

**Comment by jamespanda** [comment]
version: 1.5.3
os: FreeBSD 11.0
shell: bash (all shell return the same result)
locale: zh_TW.UTF-8

I try...(contain 下載 , 文件 and 圖片 subdirectory in home)
echo "abc\nbcd\n123\n下載\n文件\n圖片" | pick
find ~ -type d -maxdepth 1 | sort | pick

**Comment by mptre** [comment]
Ah, this has been on my todo for a long while. The current
implementation is naive and assumes every character will occupy exactly
one column once displayed. Whereas the characters in your example
occupies 3 columns. I will take a look at this later this week and let
you know when I got something working. Thanks for the bug-report.

**Comment by jamespanda** [comment]
I will wait for it
thanks

**Comment by mptre** [comment]
Please go ahead and try #185.

**Comment by jamespanda** [comment]
It works.
Thanks ^_^

**Comment by mptre** [comment]
Great! I will let you know when this is released.

**Comment by jamespanda** [comment]
OK

**Comment by jamespanda** [comment]
thanks
