### ISSUE TITLE
Some emojis cause line overflow on macOS

### ISSUE THREAD

**Issue by calleerlandsson** [calleerlandsson/pick#186]
As discussed in #185, some emojis cause lines to overflow on macOS. I've attached a screenshot below for reference.

In #185, @mptre found that this is caused by `wcwidth(3)` returning 0:

> Turns out the passing that specific emoji to `wcwidth(3)` returns 0 on macOS. This is fortunately not true for all emojis.

I found the following possibly relevant references:

- https://github.com/neovim/neovim/issues/5149
- http://denisbider.blogspot.se/2015/09/when-monospace-fonts-arent-unicode.html
- https://github.com/jquast/wcwidth/issues/19
- https://github.com/fumiyas/wcwidth-cjk

<img width="762" alt="screen shot 2017-04-18 at 09 50 39" src="https://cloud.githubusercontent.com/assets/66666/25170613/7e3fb548-24eb-11e7-9cd6-15f03bb5d9e9.png">

**Comment by mptre** [comment]
Is this still an issue in latest release of macOS? @calleerlandsson @teoljungberg

**Comment by teoljungberg** [comment]
I have not updated yet, and I'll wait a few weeks until I do so.

**Comment by DBOTW** [comment]
Not related to macOS but seems to be the same issue: https://lists.suckless.org/dev/1709/32329.html

**Comment by calleerlandsson** [comment]
I haven't updated either. I'll report back when I've done so.

**Comment by DBOTW** [comment]
Quoting https://lists.suckless.org/dev/1710/32423.html:
> As of High Sierra, many of the Wide Character spacing issues have been 
 fixed (most Emoji and all the Chinese Extentions C, D and E, now report 2)

**Comment by calleerlandsson** [comment]
I've updated now and this seems fixed! 🎉
