### ISSUE TITLE
Instructions for installation on Gentoo

### ISSUE THREAD

**Issue by hartwork** [calleerlandsson/pick#243]
Hi!

If there is interest in adding instructions on installation for Gentoo, thanks to @radhermit it's
```
sudo emerge -av sys-apps/pick
```
[for a few days now](https://github.com/gentoo/gentoo/commit/cce1a98800e06d3c4ab167171ace34f391325fe2).

Best, Sebastian

**Comment by radhermit** [comment]
As I mentioned in #241, I was waiting until our packages.gentoo.org site came back to life, which it looks it has now. I'll submit a pr shortly.
